# Generated by Django 3.0.8 on 2020-09-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200928_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
