# Generated by Django 3.0.8 on 2020-09-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200928_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sender_name',
            new_name='name',
        ),
    ]
